# PROD
FROM node:16.13.1 AS builder
ENV NODE_ENV production
WORKDIR /app
COPY package.json ./
RUN npm install 
COPY . ./
RUN npm run build
#NGINX
FROM nginx:1.19.0
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/build .
ENTRYPOINT ["nginx", "-g", "daemon off;"]